# Set server configuration
server:
  servlet:
    context-path: /api/v1
  port: 8080

# MySQL datasource configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_db
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
